export const GLOBALTYPES = {
    AUTH: "AUTH",
    RESUME_PERSONAL_DETAILS: "RESUME_PERSONAL_DETAILS",
    RESUME_EXPRIENCE_DETAILS: "RESUME_EXPRIENCE_DETAILS",
    RESUME_EDUCATION_DETAILS: "RESUME_EDUCATION_DETAILS",
    RESUME_SKILS_DETAILS: "RESUME_SKILS_DETAILS",
    RESUME_PROJECT_DETAILS: "RESUME_PROJECT_DETAILS",
    RESUME_COURSES_DETAILS: "RESUME_COURSES_DETAILS",
}